general:
  inherit_default: true
  log_level: info

exporter:
  - class: Startwind\WebInsights\Aggregation\Exporter\HtmlExporter\HtmlExporter
    options:
      outputDirectory: /var/www/results.webinsights.info/builder/test/
      theme: builder
      theme_options:
        title: "WebInsights: Report created by InsightsBuilder"
        logo: https://results.webinsights.info/assets/logo.png

  - class: Startwind\WebInsights\Aggregation\Exporter\MongoDbExporter\MongoDbExporter
    options:
      uuid: 6a4c3ec4-1a4c-4e9e-a8db-c7009481dc67
      database: classifier
      collection: builder_results


retriever:
  class: Startwind\WebInsights\Aggregation\Retriever\MongoDBRetriever
  options:
    block-size: 100
    limit: 10000
    database: classifier
    collection: raw_data
    rundId: sqm-customers-2024-02
