<?php

namespace Startwind\WebInsights\Classification\Classifier\Cms\WordPress;

use Startwind\WebInsights\Classification\Classifier\Http\Html\HtmlClassifier;
use Startwind\WebInsights\Response\Html\HtmlDocument;

class WordPressPluginClassifier extends HtmlClassifier
{
    public const TAG_PREFIX = 'wordpress:plugin:';

    private array $htmlElements = [
        'litespeed-cache' => 'LiteSpeed Cache',
        'mailchimp' => 'Mailchimp for WordPress',
        'yoast' => 'class="yoast',
        'wordfence' => 'Generated by Wordfence'
    ];

    protected function doHtmlClassification(HtmlDocument $htmlDocument): array
    {
        $tags = [];

        preg_match_all('^wp-content/plugins/(.*?)/^', $htmlDocument->getPlainContent(), $matches);

        foreach ($matches[1] as $match) {
            if (str_contains(strtolower($match), 'woocommerce')) {
                $tags[] = 'woocommerce' . self::TAG_SEPARATOR . 'plugin' . self::TAG_SEPARATOR . $match;
            } else {
                if (strlen($match) < 50) {
                    $tags[] = self::TAG_PREFIX . $match;
                }
            }
        }

        foreach ($this->htmlElements as $key => $value) {
            if ($htmlDocument->contains($value)) {
                $tags[] = self::TAG_PREFIX . $key;
            }
        }

        return $tags;
    }
}
