general:
  inherit_default: true
  log_level: info

exporter:
  class: Startwind\WebInsights\Aggregation\Exporter\HtmlExporter\HtmlExporter
  options:
    outputDirectory: /var/www/results.webinsights.info/example/wordpress-de/
    theme: webinsights_lite
    theme_options:
      logo: https://results.webinsights.info/assets/brands/logo.png
      title: "WebInsights: German WordPress websites"

retriever:
  class: Startwind\WebInsights\Aggregation\Retriever\MongoDBRetriever
  options:
    block-size: 100
    database: classifier
    collection: raw_data
    tags:
      - "cms:system:wordpress"
      - "tld:de"
